// Code generated by mockery. DO NOT EDIT.

package middlewares

import (
	context "context"

	redis "github.com/go-redis/redis/v8"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockGetterAndSetter is an autogenerated mock type for the GetterAndSetter type
type MockGetterAndSetter struct {
	mock.Mock
}

type MockGetterAndSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetterAndSetter) EXPECT() *MockGetterAndSetter_Expecter {
	return &MockGetterAndSetter_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockGetterAndSetter) Get(ctx context.Context, key string) *redis.StringCmd {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *redis.StringCmd
	if rf, ok := ret.Get(0).(func(context.Context, string) *redis.StringCmd); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StringCmd)
		}
	}

	return r0
}

// MockGetterAndSetter_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGetterAndSetter_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockGetterAndSetter_Expecter) Get(ctx interface{}, key interface{}) *MockGetterAndSetter_Get_Call {
	return &MockGetterAndSetter_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockGetterAndSetter_Get_Call) Run(run func(ctx context.Context, key string)) *MockGetterAndSetter_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGetterAndSetter_Get_Call) Return(_a0 *redis.StringCmd) *MockGetterAndSetter_Get_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGetterAndSetter_Get_Call) RunAndReturn(run func(context.Context, string) *redis.StringCmd) *MockGetterAndSetter_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: ctx, key, value, expiration
func (_m *MockGetterAndSetter) Set(ctx context.Context, key string, value interface{}, expiration time.Duration) *redis.StatusCmd {
	ret := _m.Called(ctx, key, value, expiration)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 *redis.StatusCmd
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) *redis.StatusCmd); ok {
		r0 = rf(ctx, key, value, expiration)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*redis.StatusCmd)
		}
	}

	return r0
}

// MockGetterAndSetter_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockGetterAndSetter_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value interface{}
//   - expiration time.Duration
func (_e *MockGetterAndSetter_Expecter) Set(ctx interface{}, key interface{}, value interface{}, expiration interface{}) *MockGetterAndSetter_Set_Call {
	return &MockGetterAndSetter_Set_Call{Call: _e.mock.On("Set", ctx, key, value, expiration)}
}

func (_c *MockGetterAndSetter_Set_Call) Run(run func(ctx context.Context, key string, value interface{}, expiration time.Duration)) *MockGetterAndSetter_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockGetterAndSetter_Set_Call) Return(_a0 *redis.StatusCmd) *MockGetterAndSetter_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGetterAndSetter_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) *redis.StatusCmd) *MockGetterAndSetter_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetterAndSetter creates a new instance of MockGetterAndSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetterAndSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetterAndSetter {
	mock := &MockGetterAndSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
