name: Build Image

on:
  push:
    branches:
      - "*"
      # we can limit to build on release branches only
      # - 'release/**'
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --tag wallet:latest --target prod

      - name: Remove the local image
        run: docker rmi wallet:latest
